sudo: required
cache:
  - apt

language: cpp

env:
  global:
    - CI_ROOT_PATH=$(pwd)

branches:
  only:
    - chapter06
    - chapter07
    - chapter08
    - chapter09
    - chapter10
    
>>>>>>> b9fd54e... updated README and License
notifications:
  email:
    on_success: never
    on_failure: never

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install libboost-math-dev
  - sudo apt-get install libeigen3-dev
  
before_script:
  - git submodule init
  - git submodule update
  - cd $CI_ROOT_PATH/lib/googletest/googletest
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_STANDARD=11
  - make
  - cd $CI_ROOT_PATH

script:
  - mkdir build
  - cd build
  - cmake ..
  - make && make test
