- Scan2D:
    - MAX_SCAN_RANGE: 6
    - MIN_SCAN_RANGE: 0.1

- PointCloudMap:
    - MAX_POINT_NUM: 100000
    - m_cell_thresh: 1

- PointCloudMapBS:
    - AddPoints:
        - skip:5

- SensorDataReader:
    - angle_offset: 180

- MapDrawer:
    - DrawGp:
        - step_point: 1
        - step_pose: 10
        - dd: 0.4

- SlamLauncher:
    - usleep_time: 100000

- DataAssociatorLS:
    - FindCorrespondence:
        - dist_thresh:0.2

- CostFunction:
    - m_val_thresh: 0.2

- PoseOptimizer:
    - m_val_diff_thresh: 0.000001
    - m_dd: 0.00001
    - m_dth: 0.00001
    - OptimizePose:
        - kk:0.00001
